### ISSUE TITLE
[Pre-RFC] Proto cleanup

### ISSUE THREAD

**Issue by ysimonson** [pachyderm/rfcs#3]
**Please describe the problem your proposed RFC is trying to address.**
Despite the use of gRPC/protobuf autogenerated code, there's a huge amount of boilerplate in the python and go clients. With a few changes to our gRPC/protobuf specs, we would be able to generate more idiomatic code. In tandem with custom gRPC compiler plugins, this would allow us to potentially autogenerate entire client libraries, rather than maintaining unwieldy boilerplate.

**Describe the solution you'd like**
A few changes to gRPC/protobuf code:
1) Pervasive use of comments, as higher quality gRPC compiler plugins will use these to generate docstrings.
2) [More consistent naming of enums and their values](https://github.com/pachyderm/pachyderm/issues/4130).
3) [Separate out internal-use-only protos](https://github.com/pachyderm/pachyderm/issues/3867).
4) Disambiguate function names. For example, PFS, PPS, and transactions all have a function called `DeleteAll`. This causes conflicts for client libraries, as both the go and python implementations combine all services into a single client struct/class.
5) Disambiguate function arguments. For example, `tree` vs `trees` in `FinishCommit`.
6) Break functions up into several variants when they take mutually exclusive arguments, e.g. `PutFile` and `PutFileURL` instead of just `PutFile` ([related discussion](https://github.com/pachyderm/pachyderm/issues/3859)).
7) Remove deprecated fields (e.g. `s_branch` in `CreateBranch`.)

With these changes, the code generated would be much closer to idiomatic in respective client languages. We may then be able to use gRPC compiler plugins to get the "last mile" of ergonomics and fully autogenerate client code. This would make existing, official client libraries much easier to maintain, and allow us to more trivially roll out client libraries for other languages.

**Describe alternatives you've considered**
We're currently pursuing the alternative: maintaining boilerplate in official client libraries.

**Open questions**
The biggest issue with this proposal is that some of the changes would break backwards compatibility. Is that worthwhile? Should we pursue a deprecation policy for backwards incompatible changes?

**Comment by Tryneus** [comment]
All these points sound worthwhile to me, except:

> Disambiguate function names. For example, PFS, PPS, and transactions all have a function called DeleteAll. This causes conflicts for client libraries, as both the go and python implementations combine all services into a single client struct/class.

I think we should actually namespace these by their component, then hoist all functions to the client-level unless there is a collision.  In the case of a collision, it should be possible to define a custom top-level call (like in the case of `DeleteAll`).

As for backwards compatibility - I'm not too concerned about breaking API compatibility, but we should try to not break protocol compatibility if possible.

**Comment by ysimonson** [comment]
RFC is now up: #4
